[functions]
  # Sets a custom directory for Netlify Functions
  directory = "functions"

  # Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs14.x"
  NPM_VERSION = "7.13.0"
  NODE_VERSION = "14.17.0"

#####################
#  Redirect Rules   #
#####################
[[redirects]]
  from = "/track"
  to = "/.netlify/functions/track"
  status = 200
  force = false
[[redirects]]
  from = "/identify"
  to = "/.netlify/functions/identify"
  status = 200
  force = false
